// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CronWebhook struct {
	ID             string  `json:"id"`
	URL            string  `json:"url"`
	CronExpression string  `json:"cronExpression"`
	Enabled        bool    `json:"enabled"`
	NextRun        *string `json:"nextRun,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
