// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CronWebhook struct {
	ID             string `json:"id"`
	URL            string `json:"url"`
	CronExpression string `json:"cronExpression"`
	Enabled        bool   `json:"enabled"`
}

type Mutation struct {
}

type Query struct {
}
